name: build

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: set up go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
        id: go

      - name: checkout
        uses: actions/checkout@v3

      - name: build and test
        run: go test -v ./...
        env:
          GOFLAGS: "-mod=vendor"

      - name: make release
        uses: goreleaser/goreleaser-action@v2
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
